import { google } from "googleapis";
import fs from "fs";
import path from "path";
import type { YouTubeMetadata } from "../metadata-gen/youtube-seo.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface UploadResult {
  videoId: string;
}

// ---------------------------------------------------------------------------
// Auth helper
// ---------------------------------------------------------------------------

/**
 * Build an OAuth2 client using credentials and refresh token stored in
 * environment variables.
 *
 * Required env vars:
 *   YOUTUBE_CLIENT_ID
 *   YOUTUBE_CLIENT_SECRET
 *   YOUTUBE_REFRESH_TOKEN
 */
function getAuthClient() {
  const clientId = process.env.YOUTUBE_CLIENT_ID;
  const clientSecret = process.env.YOUTUBE_CLIENT_SECRET;
  const refreshToken = process.env.YOUTUBE_REFRESH_TOKEN;

  if (!clientId || !clientSecret || !refreshToken) {
    throw new Error(
      "Missing YouTube OAuth2 credentials. " +
        "Set YOUTUBE_CLIENT_ID, YOUTUBE_CLIENT_SECRET, and YOUTUBE_REFRESH_TOKEN environment variables.",
    );
  }

  const oauth2Client = new google.auth.OAuth2(
    clientId,
    clientSecret,
    "urn:ietf:wg:oauth:2.0:oob",
  );

  oauth2Client.setCredentials({ refresh_token: refreshToken });
  return oauth2Client;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Upload a video and its thumbnail to YouTube using the Data API v3.
 *
 * The video is inserted with the provided metadata (title, description,
 * tags, category) and set to the specified privacy status.  Once the video
 * upload completes, the thumbnail is uploaded as a custom thumbnail.
 *
 * @param videoPath      Absolute path to the .mp4 file.
 * @param thumbnailPath  Absolute path to the thumbnail image (PNG/JPEG).
 * @param metadata       YouTube metadata generated by the SEO plugin.
 * @param privacyStatus  Privacy status for the uploaded video (default: "private").
 * @param language       Default language / audio language (default: "en").
 * @returns              The YouTube video ID of the uploaded video.
 */
export async function uploadToYouTube(
  videoPath: string,
  thumbnailPath: string,
  metadata: YouTubeMetadata,
  privacyStatus: "public" | "unlisted" | "private" = "private",
  language: string = "en",
): Promise<UploadResult> {
  if (!fs.existsSync(videoPath)) {
    throw new Error(`Video file not found: ${videoPath}`);
  }

  const auth = getAuthClient();
  const youtube = google.youtube({ version: "v3", auth });

  // -----------------------------------------------------------------------
  // 1. Upload video
  // -----------------------------------------------------------------------
  console.log(`[youtube-upload] Uploading video: ${path.basename(videoPath)}`);

  const videoInsertResponse = await youtube.videos.insert({
    part: ["snippet", "status"],
    requestBody: {
      snippet: {
        title: metadata.title,
        description: metadata.description,
        tags: metadata.tags,
        categoryId: metadata.categoryId,
        defaultLanguage: language,
        defaultAudioLanguage: language,
      },
      status: {
        privacyStatus,
        selfDeclaredMadeForKids: false,
      },
    },
    media: {
      body: fs.createReadStream(videoPath),
    },
  });

  const videoId = videoInsertResponse.data.id;

  if (!videoId) {
    throw new Error(
      "YouTube video upload succeeded but no video ID was returned in the response.",
    );
  }

  console.log(`[youtube-upload] Video uploaded successfully. Video ID: ${videoId}`);

  // -----------------------------------------------------------------------
  // 2. Upload thumbnail
  // -----------------------------------------------------------------------
  if (thumbnailPath && fs.existsSync(thumbnailPath)) {
    console.log(`[youtube-upload] Uploading thumbnail: ${path.basename(thumbnailPath)}`);

    try {
      await youtube.thumbnails.set({
        videoId,
        media: {
          mimeType: thumbnailPath.endsWith(".png") ? "image/png" : "image/jpeg",
          body: fs.createReadStream(thumbnailPath),
        },
      });

      console.log("[youtube-upload] Thumbnail uploaded successfully.");
    } catch (err) {
      // Thumbnail upload failure should not abort the whole process —
      // the video is already live.  Log the error and continue.
      console.error(
        `[youtube-upload] Thumbnail upload failed (video ${videoId} is still available):`,
        err,
      );
    }
  } else {
    console.log("[youtube-upload] No thumbnail file found — skipping thumbnail upload.");
  }

  return { videoId };
}
